---
title: "Blog Post 8"
author: "Kasliwal, Dakshesh; Laz, Thomas; Li, Siyan; Oh, Yunha; Xia, Chuancheng"
date: "2025-04-30"
date-modified: "2025-04-30"
draft: FALSE
---

For this week's blog post, we continued working on the final analytical aspects of our project, and began the process of making our website aesthetically appealing and presenting the data in an understandable and streamlined way. Below are answers to the three major questions for this blog post.

**How are you continuing your exploratory data analysis?**

This week, we finally got our interactive published using shinyapps.io

We also continued adding predictors to our main dataset before constructing the final statistical model. So far, we've added an estimated poverty rate and estimated proportions of each major race in each neighborhood.

We decided to model our dataset after the dataset from Homework 8. For each year, we took each borough and each UHF 42 neighborhood and filtered to include the entries where both race and sex are all. This will allow us to have one row of observation, easing the modeling process. For each row, we will have a predictor, including the ones mentioned above, and we hope to add health insurance rate, a gender proportion, age proportion, high school graduation rate, crowded housing rate, and incarceration rates.

We're also continuing to make maps displaying this information that we might use in our Big Picture page. These will be done using the UHF shapefiles we used in blog post 6.

**What is your  thesis?**

Based on the findings we've made over the course of this project, our thesis will be along the lines of: "In New York City, Hispanic, and especially black people, have increased rates of contracting HIV, compared to the other demographics in New York City."

**How do you plan to polish your visualizations and tables?**

We've been satisfied with the use of shapefiles and using a continuous gradient to color in the neighborhoods. Using the gt package to create tables is something we're also considering. We've already begun adding our own images to the website. 

The biggest way we've thought about visualization is how we can lead the readers in a logical direction with our graphs. We want to guide readers to asking themselves certain questions and then having the next graphs answer those questions and create new ones, until we've told the entire story. As we continue to finalize the exact path we want to take readers down, we'll use other methods of visualization to enhance the experience.